---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
  namespace: mailu
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mailu.github.io/helm-charts
      chart: mailu
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: mailu-charts
        namespace: flux-system
      interval: 5m
  values:
    certmanager:
      issuerName: letsencrypt-prod
    domain: mail.architectsmp.com
    hostnames:
      - mail.architectsmp.com
    initialAccount:
      domain: architectsmp.com
      username: postmaster
    logLevel: INFO
    persistence:
      size: 20Gi
      storageClass: openebs-hostpath
    roundcube:
      resources:
        requests:
          cpu: 200m
        limits:
          cpu: 400m
  valuesFrom:
    - kind: Secret
      name: "mailu-helm-values"
