---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.datadoghq.com/
      chart: datadog
      version: 2.11.5
      sourceRef:
        kind: HelmRepository
        name: datadog-charts
        namespace: flux-system
      interval: 5m
  values:
    agents:
      podAnnotations:
        container.apparmor.security.beta.kubernetes.io/agent: localhost/datadog-agent
        container.apparmor.security.beta.kubernetes.io/process-agent: localhost/datadog-agent
    datadog:
      apm:
        enabled: true
      criSocketPath: /var/run/k3s/containerd/containerd.sock
      logLevel: DEBUG
      logs:
        enabled: true
        containerCollectAll: true
      processAgent:
        enabled: true
        processCollection: true
      site: datadoghq.eu
    kubeStateMetricsEnabled: false
    targetSystem: linux
  valuesFrom:
    - kind: Secret
      name: "datadog-helm-values"
      optional: false
