---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../default
patchesStrategicMerge:
  - ./default/minecraft-creative.yaml
  - ./default/minecraft-proxy-bravo.yaml
  - ./default/minecraft-survival.yaml
