---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
spec:
  values:
    minecraftProxy:
      loadBalancerIP: 138.201.203.179
      memory: 512M
      serviceAnnotations:
        metallb.universe.tf/allow-shared-ip: dev-proxy