---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-survival
spec:
  values:
    nameOverride: dev
    persistence:
      dataDir:
        size: 1Gi
    resources:
      requests:
        memory: 1024Mi
      limits:
        memory: 2048Mi
    minecraftServer:
      version: "1.17"
      memory: 1G
      jvmOpts: "-javaagent:dd-java-agent.jar -Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256"
      extraEnv:
        DD_PROFILING_ENABLED: "true"
        DD_LOGS_INJECTION: "true"
      extraPorts:
        - name: map
          containerPort: 8100
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 8100
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              external-dns.alpha.kubernetes.io/hostname: map-dev.architectsmp.com
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            hosts:
              - name: map-dev.architectsmp.com
                path: /
        - name: prometheus
          containerPort: 9225
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
        - name: voice
          protocol: UDP
          containerPort: 60606
          service:
            enabled: true
            annotations:
              metallb.universe.tf/allow-shared-ip: dev-proxy
            type: LoadBalancer
            loadBalancerIP: 138.201.203.179
            port: 60606
          ingress:
            enabled: false
