---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-survival
spec:
  values:
    nameOverride: dev
    persistence:
      dataDir:
        size: 1Gi
    resources:
      requests:
        memory: 1024Mi
      limits:
        memory: 2048Mi
    minecraftServer:
      memory: 1G
      jvmOpts: "-javaagent:dd-java-agent.jar"
      extraEnv:
        DD_PROFILING_ENABLED: "true"
        DD_LOGS_INJECTION: "true"
      extraPorts:
        - name: prometheus
          containerPort: 9225
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
