---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: architectsmp-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/ArchitectSMP/charts
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include releases directory
    !/releases/
