{
 "title": "Minecraft",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(mc_players_total, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_players_total{container=~\"$container\"}",
     "legendFormat": "Unique"
    },
    {
     "expr": "sum(mc_players_online_total{container=~\"$container\"}) by (world)",
     "legendFormat": "Online ({{world}})"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mc_players_online_total{container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mc_tps{container=~\"$container\"}"
    }
   ]
  },
  {
   "title": "Players per world",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "mc_players_online_total{container=~\"$container\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks_total{container=~\"$container\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mc_jvm_memory{type='max', container=~\"$container\"}",
     "legendFormat": "Allocated - {{container}}"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', container=~\"$container\"} - scalar(mc_jvm_memory{type='free', container=~\"$container\"})",
     "legendFormat": "Used - {{container}}"
    }
   ]
  },
  {
   "title": "Tick Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds per tick" }
   ],
   "targets": [
    {
     "expr": "mc_tick_duration_max{container=~\"$container\"}/1e6",
     "legendFormat": "Max - {{container}}"
    },
    {
     "expr": "mc_tick_duration_average{container=~\"$container\"}/1e6",
     "legendFormat": "Avg - {{container}}"
    }
   ]
  },
  {
   "title": "Tickrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mc_tps{container=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (mc_entities_total{container=~\"$container\"}) by (world, level, type)",
     "legendFormat": "{{world}}:  {{type}}"
    }
   ]
  },
  {
   "title": "Villagers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (mc_villagers_total{container=~\"$container\"}) by (world, level, profession)",
     "legendFormat": "{{world}}:  {{profession}}  (lv{{level}})"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (mc_entities_total{container=~\"$container\"}) by (world)",
     "legendFormat": "{{world}}_total"
    }
   ]
  }
 ]
}