---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-creative
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 2.1.4
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    # ref: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
    image: itzg/minecraft-server
    imageTag: 1.8.0-adopt13
    persistence:
      storageClass: local-path
      dataDir:
        enabled: true
        size: 10Gi
    resources:
      requests:
        memory: 8192Mi
      limits:
        memory: 10240Mi
    extraEnv:
      USE_AIKAR_FLAGS: TRUE
    minecraftServer:
      eula: "TRUE"
      type: PAPER
      mode: creative
      onlineMode: false
      paperDownloadUrl: https://papermc.io/api/v1/paper/1.16.4/latest/download
      forceReDownload: true
      memory: 8G
      difficulty: hard
      maxTickTime: -1
      motd: "Architect SMP Creative"
      serviceType: ClusterIP
      dynmap:
        service:
          enabled: true
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - name: map-creative.architectsmp.com
              path: /
