---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-survival
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./releases/minecraft-3.3.0.tgz
      sourceRef:
        kind: GitRepository
        name: architectsmp-itzg-charts
        namespace: flux-system
      interval: 5m
  values:
    # ref: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
    image: itzg/minecraft-server
    imageTag: 2021.16.0-java16-openj9
    persistence:
      storageClass: openebs-hostpath
      dataDir:
        enabled: true
        size: 10Gi
    resources:
      requests:
        memory: 8192Mi
      limits:
        memory: 10240Mi
    podAnnotations:
      backup.velero.io/backup-volumes: datadir
    extraEnv:
      USE_AIKAR_FLAGS: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
    minecraftServer:
      eula: "TRUE"
      onlineMode: false
      version: "1.17"
      mode: survival
      forcegameMode: false
      type: PAPER
      pvp: true
      forceReDownload: true
      difficulty: hard
      playerIdleTimeout: 300
      levelSeed: "237442222458213"
      maxPlayers: 40
      maxWorldSize: 100000
      viewDistance: 4
      maxTickTime: -1
      memory: 8G
      motd: '"\\u00A78-\\u00A7r--\\u00A78-\\u00A7r [ \\u00A7b\\u00A7lArchitect SMP\\u00A7r ] \\u00A78-\\u00A7r--\\u00A78-\\u00A7r [ \\u00A7a\\u00A7lSurvival \\u00A7r] \\u00A78-\\u00A7r--\\u00A78-\\u00A7r\\n\\u00A78-\\u00A7r--\\u00A78-\\u00A7r [ \\u00A7eNews:\\u00A7r ] --\\u00A7r [ \\u00A7ddonate.architectsmp.com\\u00A7r ] \\u00A78-\\u00A7r--\\u00A78-\\u00A7r"'
      serviceType: ClusterIP
      rcon:
        enabled: true
        serviceType: ClusterIP
      extraPorts:
        - name: map
          containerPort: 8123
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 8123
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              external-dns.alpha.kubernetes.io/hostname: map.architectsmp.com
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            hosts:
              - name: map.architectsmp.com
                path: /
        - name: prometheus
          containerPort: 9225
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
