---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-database
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 2.1.7
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: bitnami/mariadb
      tag: 10.4.17-debian-10-r74
    auth:
      rootPassword: architectsmp
      database: architectsmp
    primary:
      persistence:
        enabled: true
        storageClass: local-path
        size: 8Gi
