---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./releases/bungee-1.3.tgz
      sourceRef:
        kind: GitRepository
        name: architectsmp-charts
        namespace: flux-system
      interval: 5m
  values:
    image: itzg/bungeecord
    imageTag: 1.5.0-adopt13
    persistence:
      storageClass: local-path
      dataDir:
        enabled: true
    bungeeCord:
      type: VELOCITY
      velocityVersion: 1.1.3
      serviceType: LoadBalancer
      loadBalancerIP: 138.201.203.147
      memory: 512M
