---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: bungee-deployment
      version: 2.2
      sourceRef:
        kind: GitRepository
        name: architectsmp-charts
        namespace: flux-system
      interval: 5m
