---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: default
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: minecraft-proxy
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image: itzg/bungeecord
    imageTag: 1.5.0-adopt13
    persistence:
      storageClass: openebs-hostpath
      dataDir:
        enabled: true
    minecraftProxy:
      type: WATERFALL
      waterfallVersion: 1.17
      waterfallBuildId: 438
      serviceType: LoadBalancer
      loadBalancerIP: 138.201.203.183
      externalTrafficPolicy: Cluster
      memory: 2G
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceAnnotations:
        metallb.universe.tf/allow-shared-ip: proxy
