---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promcord
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: promcord
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: biospheere/promcord
      tag: latest
    prometheus:
      podMonitor:
        enabled: true
  valuesFrom:
    - kind: Secret
      name: "promcord-helm-values"
      optional: false
