---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.4.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 138.201.203.147/32
            - 138.201.203.179/32
            - 138.201.203.183/32
            - 138.201.203.178/32
    networkPolicy:
      enabled: true
    prometheusRule:
      enabled: true
    controller:
      image:
        registry: docker.io
        repository: metallb/controller
        tag: v0.10.2
      prometheus:
        serviceMonitor:
          enabled: true
    speaker:
      image:
        registry: docker.io
        repository: metallb/speaker
        tag: v0.10.2
      prometheus:
        serviceMonitor:
          enabled: true
